### ISSUE TITLE
部分csv数据错误

### ISSUE THREAD

**Issue by StewartXiang** [Werneror/Poetry#7]
清_2.csv
360行左右，《重赋》
466行左右，《台南盐政归台道督办而积弊甚深皆由委员少廉洁者殊可慨也》
清末民国初.csv
8023行左右，《次林十暮春瑞轩养病即事韵》
8124行左右，《补祝叔臧先生四十双寿》
（github 萌新，想共同维护这个库

**Comment by StewartXiang** [comment]
(看了commit，发现有修改，但我也不知道为啥我下载的就有问题。。关闭了（

**Comment by StewartXiang** [comment]
（还有一个问题，就是总共有6k+的题目名称中，有大概1176首的题目里面，带有中文字符的空格（全角），我想写一个脚本把它们全部替换为半角（或者用一个能全部读取内容的编辑器

**Comment by zgx030030** [comment]
直接用正则replace就行了吧

**Comment by Werneror** [comment]
[这个 PR](https://github.com/Werneror/Poetry/pull/6) 解决了此 Issue。
