### ISSUE TITLE
小程序调用

### ISSUE THREAD

**Issue by QiyaoShn** [Werneror/Poetry#9]
请问一下您https://api.nextrt.com/V1/Gushi/{Type}/{Value} 后面的Type和Value怎么填啊，我微信小程序成功调用到您的API了，就是渲染不出来具体的内容，想调用特定的古诗的api，随机的不好渲染啊，Type和Value上随便填两个数字每次刷新页面调到的都是不同的古诗。

**Comment by Werneror** [comment]
我不记得 https://api.nextrt.com/V1/Gushi/ 是我做的 API，可能是别人用这个仓库的数据做的 API？
